ALTER TABLE TrackScores ADD COLUMN NotesHit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TrackScores ADD COLUMN TotalNotes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TrackScores ADD COLUMN Timestamp INTEGER NOT NULL DEFAULT 0;