CREATE TABLE Songs (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ChartHash VARCHAR(255) NOT NULL UNIQUE,
    Name VARCHAR(255) NOT NULL,
    RelativePath VARCHAR(255) NOT NULL
);

CREATE TABLE TrackScores (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    SongId INTEGER NOT NULL,
    TrackName VARCHAR(255) NOT NULL,
    Score INTEGER NOT NULL,
    Fingerprint VARCHAR(255) NOT NULL,
    FOREIGN KEY(SongId) REFERENCES Songs(Id)
    UNIQUE(SongId, TrackName)
);
